FROM alpine:3.22

RUN apk --no-cache add \
    make \
    texlive \
    texlive-most \
    texlive-langextra \
    texlive-xetex \
    texlive-luatex \
    fontconfig \
    ghostscript \
    font-noto-cjk

WORKDIR /work
